name: Front Deployment

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: react build & deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout Github Action
        uses: actions/checkout@v3
      
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: install npm dependencies
        run: npm install
        
      - name: react build
        run: npm run build
        env:
            CI: ""
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-northeast-2
      
      - name: Print environment variables for debugging
        run: |
          echo "BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}"
          echo "ADDITIONAL_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME2 }}"
      
      - name: Upload to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          aws s3 sync ./build s3://$BUCKET_NAME


      # 추가 버킷에 build 파일을 올립니다.

      - name: Upload to additional S3
        env:
          ADDITIONAL_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME2 }}
        run: |
          aws s3 sync ./build s3://$ADDITIONAL_BUCKET_NAME
      
      - name: CloudFront Invalidation
        env:
          CLOUD_FRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_ID --paths /*
